# Generated by Django 3.0.4 on 2020-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('offer', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
