# Generated by Django 3.0.4 on 2020-03-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
